### ISSUE TITLE
Require sign in / registration only upon submitting the request offers form

### ISSUE THREAD

**Issue by Teekola** [Teekola/firewood-marketplace#5]
### Task
The account creation / sign in should be only required before submitting, but sign in should be allowed earlier as well to automatically fill form fields.

### Steps
- [x] Remove the auth check and sign in redirect
- [x] Add deafult user object and determine the geolocation data through calling api
- [x] Add suggestion text for sign in to top of the request offers form if the user is not signed in: "do you already have an account? Sign in to automatically fill data."
- [x] Modify the submit step to require sign in or create account upon submitting. if the user is not signed in, the button says sign in or register to submit, and if they are signed in, it is only "submit". After submitting, sign in / register flow is run, after which the form is submitted. Should ensure that refreshing the page still makes everything work correctly!
- [x] Ensure that the page height is big enough to avoid weird overlaying layout when for instance error messages are present!
- [x] Make sure that the data on the form is populated when user signs in from the form suggestion
- [x] Test manually that the implementation works as expected
