### ISSUE TITLE
Implement seller dashboard

### ISSUE THREAD

**Issue by Teekola** [Teekola/firewood-marketplace#6]
### Task
- Quotation Requests and sent offers and their status
- Modifying seller information and settings

### Steps
- [x] add token update logic for updating the token after registering
- [x] add all information update sections with forms for saving changes
- [x] add offer creation form
- [x] add quotation request rejection functionality
- [x] add pagination or infinite scroll
- [x] add rejected quotation requests view functionalities
- [x] add offer update functionality, enabled for both pending and rejected offers
- [x] add has seen functionality for the seller on changed items with red marks
